networks:
  prisma:
    driver: bridge
services:
  transform:
    build:
      context: .
      dockerfile: Dockerfile.pipeline_api
      args:
        COMMIT_TAG: local
    env_file:
      - .env
    volumes:
      - ./.aws:/app/.aws
      - ./viz:/app/viz
    # depends_on:
    #   api:
    #     condition: service_healthy
    networks:
      - prisma

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #     args:
  #       COMMIT_TAG: local
  #       API_HOST: ${API_HOST:-0.0.0.0}
  #       API_PORT: ${API_PORT:-8000}
  #   environment:
  #     - GIT_COMMIT_TAG=local
  #   ports:
  #     - "8000:8000"
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/version"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3
  #   networks:
  #     - prisma