networks:
  frontend: # docker network create -d bridge frontend
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:3001:3001
    restart: unless-stopped
    networks:
      - frontend